name: Build iOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build Game
        uses: Ayane-Satomi/renpy-build-action@v1.5.0
        with:
          sdk-version: '8.5.0' # Укажите здесь свою версию Ren'Py
          project-path: '.'
          ios: true
