name: Build iOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download Ren'Py
        run: |
          # Мы скачиваем актуальную версию 8.2.1. Если у вас 7-я версия, замените ссылку.
          curl -L https://renpy.org -o renpy.zip
          unzip -q renpy.zip
          mv renpy-8.2.1-sdk renpy-sdk

      - name: Build iOS App
        run: |
          # Эта команда запустит сборку из корня вашего репозитория
          ./renpy-sdk/renpy.sh . ios deploy . --signing-group "NONE"
