name: Build iOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Ren'Py Build Action
        uses: mal some/renpy-build-action@v2
        with:
          sdk-version: '8.5.0' # Убедитесь, что эта версия совпадает с вашей
          project-path: '.'
          # Собираем именно для iOS
          ios: true
